title: "kourpoiKomment"
email: aaaa@gmail.com
timezone: Europe/Paris
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Antoine
paginate: 30
disqus: 'demowebsite'
locale: fr_fr
lang: fr_fr
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/avatars/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  antoine:
    name: Antoine GIRET
    display_name: Antoine
    avatar: 'assets/images/avatars/antoine_giret.jpg'
    email: wowthemesnet@gmail.com
    web: https://www.linkedin.com/in/antoinegiret/
    twitter: https://twitter.com/antoinegiret
    linkedin: https://www.linkedin.com/in/antoinegiret/
    description: "Conseil et accompagnement à la définition de stratégies de rediretion écologique des organisations."

# Social
social:
  # instagram: https://www.instagram.com/bootstrapstarter/
  # facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/antoinegiret
  linkedin: https://www.linkedin.com/in/antoinegiret/

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
